import { demoRecords, demoReport } from "@/lib/demo";
import type { SecondOpinionReport } from "@/lib/schemas";

export const demoRecordsVi = demoRecords.map(record => ({ ...record, extraction: { ...record.extraction,
  documentType: record.id === "primary-note" ? "Ghi chú khám ban đầu" : record.id === "lab-report" ? "Phiếu xét nghiệm" : "Siêu âm tuyến giáp",
  patientSummary: record.id === "primary-note" ? "Người bệnh giả lập ghi nhận mệt mỏi tám tuần, hồi hộp từng cơn, không chịu được nóng và sụt cân ngoài ý muốn. Chẩn đoán tạm thời là lo âu." : record.id === "lab-report" ? "Xét nghiệm tuyến giáp cho thấy TSH giảm và FT4 tăng." : "Siêu âm mô tả tuyến giáp hơi to, cấu trúc không đồng nhất và không có nhân ưu thế."
} }));

export const demoReportVi: SecondOpinionReport = { ...demoReport,
  headline: "Chẩn đoán lo âu chưa giải thích đầy đủ các bất thường tuyến giáp khách quan.", executiveSummary: "Một số triệu chứng có thể gặp trong lo âu, nhưng TSH giảm, FT4 tăng, mạch nhanh kéo dài, sụt cân và thay đổi trên siêu âm cần được bác sĩ đánh giá sớm về khả năng cường giáp. Hồ sơ hiện có chưa đủ để xác định nguyên nhân.",
  redFlags: [{...demoReport.redFlags[0],title:"Cần hỗ trợ khẩn cấp khi có triệu chứng tim hoặc hô hấp nặng",reason:"Hồ sơ ghi nhận mạch nhanh và hồi hộp. Nhịp tim rất nhanh hoặc không đều kéo dài kèm đau ngực, ngất, khó thở nặng, lú lẫn hoặc sốt cao có thể cần đánh giá cấp cứu.",action:"Nếu đang có bất kỳ triệu chứng nào trên, hãy đi khám trực tiếp ngay hoặc gọi cấp cứu. Tại Việt Nam, gọi 115."}],
  caseSnapshot:{demographics:"Người trưởng thành giả lập, khoảng 30–39 tuổi; không có thông tin về giới tính liên quan đến chăm sóc.",currentDiagnosis:"Lo âu, được ghi nhận là chẩn đoán tạm thời.",currentTreatment:"Có kê propranolol 10 mg đường uống khi cần; chưa rõ chỉ định và mức độ sử dụng thực tế.",keySymptoms:["Hồi hộp trong tám tuần","Không chịu được nóng","Mệt mỏi","Sụt 4 kg ngoài ý muốn"]},
  timeline:demoReport.timeline.map((item,i)=>({...item,event:["Theo ghi nhận, các triệu chứng bắt đầu xuất hiện.","Lần khám ban đầu ghi nhận mạch nhanh, run tay và chẩn đoán tạm thời là lo âu.","TSH giảm và FT4 tăng.","Siêu âm cho thấy thay đổi lan tỏa ở tuyến giáp, không có nhân ưu thế."][i],significance:["Các triệu chứng toàn thân kéo dài xuất hiện trước chẩn đoán tạm thời.","Lo âu có thể trùng lặp triệu chứng, nhưng cũng cần xem xét nguyên nhân thực thể.","Kiểu xét nghiệm này ủng hộ tình trạng tăng hoạt tuyến giáp và không phù hợp với lo âu đơn thuần.","Hình ảnh ủng hộ có liên quan tuyến giáp nhưng không xác định được nguyên nhân."][i]})),
  evidenceFor:[{...demoReport.evidenceFor[0],point:"Hồi hộp và mệt mỏi có thể xuất hiện trong lo âu.",significance:"Các triệu chứng này trùng lặp với chẩn đoán tạm thời nhưng không đặc hiệu."}], evidenceAgainst:[{...demoReport.evidenceAgainst[0],point:"TSH thấp và FT4 cao.",significance:"Các bất thường tuyến giáp khách quan không được giải thích bằng lo âu đơn thuần."},{...demoReport.evidenceAgainst[1],point:"Sụt cân, không chịu được nóng, run tay và mạch nhanh xuất hiện thành cụm.",significance:"Kiểu triệu chứng này cần được đánh giá nguyên nhân y khoa."}],
  alternativeConsiderations:[{...demoReport.alternativeConsiderations[0],name:"Cường giáp, chưa xác định nguyên nhân",rationale:"Triệu chứng và xét nghiệm phù hợp với tình trạng dư thừa hormone tuyến giáp.",whatWouldClarify:"Lặp lại xét nghiệm chức năng tuyến giáp, kháng thể, thăm khám và theo dõi theo chỉ định bác sĩ."},{...demoReport.alternativeConsiderations[1],name:"Viêm tuyến giáp",rationale:"Thay đổi lan tỏa và xét nghiệm bất thường có thể gặp trong viêm, nhưng hồ sơ còn thiếu dữ liệu.",whatWouldClarify:"Bệnh sử, thăm khám, xu hướng xét nghiệm và các kiểm tra do bác sĩ lựa chọn."}],
  missingInformation:[{...demoReport.missingInformation[0],item:"Lặp lại TSH, FT4 và FT3",whyItMatters:"Giúp xác nhận bất thường còn tồn tại và mô tả rõ hơn kiểu rối loạn tuyến giáp."}], contradictions:[{...demoReport.contradictions[0],description:"Chẩn đoán lo âu tạm thời được ghi trước khi tích hợp kết quả tuyến giáp bất thường.",itemsInConflict:["Đánh giá lo âu tạm thời","Bảng xét nghiệm tuyến giáp bất thường"],howToClarify:"Hỏi liệu chẩn đoán đã được xem xét lại sau khi có kết quả xét nghiệm hay chưa."}],
  treatmentConsiderations:[{...demoReport.treatmentConsiderations[0],topic:"Sử dụng propranolol",discussionPoint:"Hỏi thuốc nhằm kiểm soát triệu chứng nào, nên dùng với tần suất ra sao và cần theo dõi gì.",caution:"Không bắt đầu, dừng hay đổi liều dựa trên báo cáo này; hãy trao đổi với bác sĩ."}], questionsForDoctor:["Kết quả tuyến giáp có làm thay đổi chẩn đoán lo âu tạm thời không?","Nguyên nhân nào có thể tạo ra kiểu hormone này và xét nghiệm nào giúp phân biệt?","Bao lâu nên kiểm tra lại tuyến giáp và mạch?","Triệu chứng nào cần khám khẩn hoặc cấp cứu?"], uncertainty:"Bản đánh giá không thể xác định nguyên nhân xét nghiệm bất thường hay xác nhận chẩn đoán. Nội dung chỉ dựa trên ba hồ sơ giả lập.", limitations:["Không có thăm khám đầy đủ.","Không có xét nghiệm tuyến giáp lặp lại hoặc kháng thể.","Thông tin sử dụng thuốc và tiền sử có thể chưa đầy đủ."]
};
